### ISSUE TITLE
Is the game completable? (even with bugs or missing features)

### ISSUE THREAD

**Issue by neuromancer** [scemino/engge#171]
Now that engge supports savegames, it seem practical to play the entire game. Is it completable right now? Also, could be possible to update README with a more detailed description of how completable it is?

**Comment by scemino** [comment]
That's an excellent question. This is what I try to do these days, I'm focusing on being able to finish a game even if there are still a lot of weird behaviors or graphical issues.
The problem is when I found and fix a blocking issue, I can create a regression and I'm not sure if I start from the beginning I don't face any new issues...
But still, I try to finish the game with engge, and when it will be done, I will release a new version. Today I'm able to play until arriving to the hotel. I have to go further...

**Comment by Mac1512** [comment]
That is why I am at the beginning, my intention is to advance from the beginning onwards and see what possible bugs I can find. To date with each new commit, I try to start from the beginning and I think that now it is more or less stable to continue forward.

There have been regressions and there was instability derived from the saved games. So I have considered not moving forward until now.

I am going to be making a list of the observed failures and I think that here it can be the place to go commenting on them and, according to the failure, open a new issue.

For example, we still have to solve the problem with the location of the actors; When Boris talks to Willie in Part 1, he covers Willie. Even the interaction between the two is still incorrect with respect to the original. In the original, most of the options lead to dialogue between the two. Also the positions of other actors are incorrect, for example when Ray and Reyes give each other objects, etc. Although this is a minor evil, since it does not matter when it comes to gameplay.

Another thing that I have observed is that in part 2, the Pigeon Brother´s van when in motion floats in the air, the wheels do not appear. Perhaps this is corrected when solving another problem or on the contrary scemino should dedicate exclusively to it. Although to play the game this is still not important.

I have not advanced too much in Thimbleweed Park and my intention is to finish it from engge :)

**Comment by scemino** [comment]
It was really painful, but I reached "Part 4: The Will"...

**Comment by Mac1512** [comment]
Brilliant !!! Less is left 👍 

:)

**Comment by scemino** [comment]
OK, I just finished the game 🎉 🍾

**Comment by scemino** [comment]
I need to fix #193 before releasing version 0.6

**Comment by scemino** [comment]
OK, #193 is done, do you some more time to test ? I'm ready to release version 0.6

**Comment by Mac1512** [comment]
Genial !!! I just downloaded the commit: (https://github.com/scemino/engge/commit/8c14b3996b55951db1595dd06191607fd135993b) I'm going to try :)

**Comment by Mac1512** [comment]
I've been testing the commit: (https://github.com/scemino/engge/commit/8c14b3996b55951db1595dd06191607fd135993b)

I have reached part 3, but I have encountered a series of bugs along the way. Some of smaller and others of greater importance.

Step to detail the most important:

- In the sheriff's office, When I selected Ray, I couldn't select Reyes again. I don't know if this error comes from a saved game or not. Since it loads game before reaching that area. I've been playing with Ray from that moment until they hit him on the head. From there, engge has selected Reyes, and I have played with Reyes from that moment until reaching part 3. I have not been able to perform the part in which Ray is in the sewers, etc., since it does not allow me to select her from Again, but still, I've got to part 3. At this point Ray has appeared again. I have not handled Delores either, although this I must check if I can do it in part 3, since I have not spoken with her sister.

- Reyes goes through the water leak that the Pigeon brother´sare fixing in part two and accesses A-Street (which should not be until the leak is fixed), but cannot cross the water again. Therefore, I must load a save game.

- In Nikel news, Reyes talks to the reporter, the text is seen but the reporter is not seen.

- There is an error when using the sheriff's radio, when using more than one sentence, to form a complete sentence. It does not allow completing the sentence.

- The county map is already in the photocopier, Reyes gets 4 copies of it. This is an error, since it is necessary to do a series of steps to achieve it.

- There are many flaws with the sound. in the log you can see the message:

                    cannot play sound no more channel available.

These are the most important failures that I have seen when testing, even so it has let me get to part 3. I think it shouldn't have been able to get there and instead it has left me.

There are many minor bugs that I have not listed here. My intention at the moment is not to open an issue, since I want to test the last commit you have added and play without recording the game as much as I can, to check if I get those errors.

**Comment by scemino** [comment]
I created the issue #205, I will check the other issues later. Thank you @Mac1512

**Comment by Mac1512** [comment]
There is no reason to thank ... I am happy to help :)

As soon as I have a moment I will test the new changes you have made in the commits. And I will comment on the result. Perhaps some of the errors that you have not been able to reproduce have already been corrected and if not, I will provide you with captures or whatever I can.

I saw that you had added the option to stop the sounds, although I thought you had already solved the number of free channels.

**Comment by scemino** [comment]
OK let me know if it's OK for you, if there are no big issues, I'm ready (again) to release 😉

**Comment by Mac1512** [comment]
I haven't been able to test much, but I have noticed a bug when testing the last commit (https://github.com/scemino/engge/commit/f49949dc4bc56cf7fd8e08eda6c18ec35e884939). This bug blocks engge. I have opened the issue https://github.com/scemino/engge/issues/210

**Comment by scemino** [comment]
I fixed it

**Comment by Mac1512** [comment]
I have been testing the last commit (https://github.com/scemino/engge/commit/93ecfc3e81e05f5fadd7a8eb8da6376b247d96c2), and I have observed glitches, I have played until the end of the Ransome clown part, from that point the engge engine, has crashed I have opened the issue (https://github.com/scemino/engge/issues/211)

**Comment by scemino** [comment]
Fixed

**Comment by Mac1512** [comment]
Thank you !!  :)

I have discussed the problem.

**Comment by scemino** [comment]
It seems to be minor bugs, if you're ok, I want to release 0.6.0, there are still bugs, but it can be interesting to release 0.6.0.
I just want to fix now big crashes or bugs that prevent to progress in the game.

**Comment by Mac1512** [comment]
I see it correct. The bugs that are observed for release 0.7.0
