### ISSUE TITLE
Layer still wrong

### ISSUE THREAD

**Issue by scemino** [scemino/engge#52]
As you can see in this screenshot, some layers are still wrong:
<img width="509" alt="engge_bug_layer" src="https://user-images.githubusercontent.com/643384/68508510-d9aeef80-026e-11ea-8ef5-44edbbe0576f.png">

**Comment by Mac1512** [comment]
In windows, the layer you are commenting on, works correctly

I have started from the file "engge.nut" which loads the room "highwayMainStreetDoor" and click on the Delores icon, and when advancing through the room I get the image you put and it turns out like this:

![Delores_layer](https://user-images.githubusercontent.com/2179224/77239112-33d59f00-6bd7-11ea-90e6-01023fd5cde9.PNG)


For me it is correct.

I do not know if you have seen any other incorrect layer, if so, put it and I will check it.

**Comment by scemino** [comment]
Yes I fixed this room in this commit a0541a4 but still layers are wrong in TraillerAlley for example, this is why I didn't close this issue.

**Comment by Mac1512** [comment]
Ok, thanks for the clarification
